FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./rest-api/cmd/

FROM scratch
COPY --from=builder /app/main /rest-api
EXPOSE 8080
ENTRYPOINT ["/rest-api"]
