FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./rest-api/cmd/

FROM scratch
COPY --from=builder /app/main /rest-api
ARG REST_API_PORT=8080
ENV REST_API_PORT=${REST_API_PORT}

EXPOSE ${REST_API_PORT}
ENTRYPOINT ["/rest-api"]
