FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./batch-receiver/cmd/

FROM scratch
COPY --from=builder /app/main batch-receiver
EXPOSE 8090
ENTRYPOINT ["/batch-receiver"]
