FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./batch-receiver/cmd/

FROM scratch
COPY --from=builder /app/main batch-receiver
ARG BATCH_RECEIVER_PORT=8090
ENV BATCH_RECEIVER_PORT=${BATCH_RECEIVER_PORT}

EXPOSE ${BATCH_RECEIVER_PORT}
ENTRYPOINT ["/batch-receiver"]
